name: Keep alive
on:
  schedule:
    - cron: "*/5 * * * *"
permissions:
  actions: write
jobs:
  keepalive-job:
    name: Keepalive Workflow
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2
