name: Keep alive
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Keep repository active
        run: |
          date > last-update.txt
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add last-update.txt
          git commit -m "chore: keep repository active $(date)"
          git push
